### ISSUE TITLE
Sidebar styling changed in newer versions of react modules

### ISSUE THREAD

**Issue by Etzeitet** [miguelgrinberg/react-microblog#4]
I started working through your excellent tutorial when I noticed in Chapter 3 and 4, my Sidebar links did not have the same styling as in your screen shots.

Screen shot from Chapter 4:

![image](https://user-images.githubusercontent.com/5340057/187050464-a841b27b-6d0b-4a0a-9d84-ebb96b806ade.png)

My version:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/5340057/187049543-f346737c-131f-4c60-8ad4-8002c8e5dd6e.png">

As you can see, the active highlighting in my version has no extra padding or margin around the link text.

Initially I thought I had made a mistake somewhere in my project, but I copied and pasted your code into my own project and the issue remained. 

The only way I found to make the styling of the Sidebar Nav items match your screenshots was to `npm install` using your `project.json` from this repo. 

To confirm it was due to module version difference (and not just something odd about my project), I cloned your repo, checked out the `v0.4` tag, copied in *my* `package.json` into your repo and `npm installed` from that. The same styling issue occurred.

I do not know *which* module is causing the problem (presumably `react-bootstrap`), and my knowledge of node and react are not good enough for me to work out where the difference is coming from.

I am raising this as an issue as I am sure others will notice the difference in styling and be confused by it.

Your package.json:

```json
{
  "name": "microblog-react",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^14.0.0",
    "bootstrap": "^5.1.3",
    "react": "^18.0.0",
    "react-bootstrap": "^2.2.3",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.3.0",
    "react-scripts": "5.0.0",
    "serve": "^13.0.2",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

And my package.json (as of 27 August 2022):

```py
{
  "name": "react-microblog",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "bootstrap": "^5.2.0",
    "react": "^18.2.0",
    "react-bootstrap": "^2.5.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.3.0",
    "react-scripts": "5.0.1",
    "serve": "^14.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

**Comment by miguelgrinberg** [comment]
The difference is that you are using bootstrap 5.2 and I styles the sidebar on top of bootstrap 5.1. For some reason they have reduced the padding on navigation links in the new release.

You can add some padding and make it look the same as my screenshot by editing the `.Sidebar a` definition in index.css:

```css
.Sidebar a {
  color: #444;
  padding: 8px;   // <-- add this line
}
```

**Comment by Etzeitet** [comment]
Thanks for looking into this. I can confirm your suggestion works.
